# Androguard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Androguard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Androguard.  If not, see <http://www.gnu.org/licenses/>.

# frameworks/base/core/res/AndroidManifest.xml

# This list is also updated periodically with scripts/update_android_permissions.py
# ######################################### PERMISSIONS ###################
# flake8: noqa
DVM_PERMISSIONS = {
    'MANIFEST_PERMISSION': {
        'SEND_SMS': ['dangerous', '发送短信', '允许应用程序发送短信。恶意应用程序可能会在未经您确认的情况下发送短信，从而导致您产生费用。'],
        'SEND_SMS_NO_CONFIRMATION': ['dangerous', '发送短信', '通过消息应用发送短信，无需用户输入或确认。'],
        'CALL_PHONE': ['dangerous', '直接拨打电话', '允许应用程序在不经过您的操作的情况下拨打电话。恶意应用程序可能会导致您的电话账单上出现意外的通话费用。请注意，此权限不允许应用程序拨打紧急电话号码。'],
        'RECEIVE_SMS': ['dangerous', '接收短信', '允许应用程序接收和处理短信。恶意应用程序可能会监控您的短信或在不向您显示的情况下删除它们。'],
        'RECEIVE_MMS': ['dangerous', '接收彩信', '允许应用程序接收和处理彩信。恶意应用程序可能会监控您的信息或在不向您显示的情况下删除它们。'],
        'READ_SMS': ['dangerous', '读取短信或彩信', '允许应用程序读取存储在您手机或SIM卡上的短信。恶意应用程序可能会读取您的机密信息。'],
        'WRITE_SMS': ['dangerous', '编辑短信或彩信', '允许应用程序写入存储在您手机或SIM卡上的短信。恶意应用程序可能会删除您的信息。'],
        'RECEIVE_WAP_PUSH': ['dangerous', '接收WAP推送', '允许应用程序接收和处理WAP消息。恶意应用程序可能会监控您的消息或在不向您显示的情况下删除它们。'],
        'READ_CONTACTS': ['dangerous', '读取联系人数据', '允许应用程序读取存储在您手机上的所有联系人（地址）数据。恶意应用程序可能会使用此权限将您的数据发送给其他人。'],
        'WRITE_CONTACTS': ['dangerous', '写入联系人数据', '允许应用程序修改存储在您手机上的联系人（地址）数据。恶意应用程序可能会使用此权限删除或修改您的联系人数据。'],
        'READ_PROFILE': ['dangerous', '读取用户个人资料数据', '允许应用程序读取用户的个人资料数据。'],
        'WRITE_PROFILE': ['dangerous', '写入用户个人资料数据', '允许应用程序写入（但不能读取）用户的个人资料数据。'],
        'READ_SOCIAL_STREAM': ['dangerous', '从用户的社交流中读取', '允许应用程序从用户的社交流中读取数据。'],
        'WRITE_SOCIAL_STREAM': ['dangerous', '写入用户的社交流', '允许应用程序写入（但不能读取）用户的社交流数据。'],
        'READ_CALENDAR': ['dangerous', '读取日历事件', '允许应用程序读取存储在您手机上的所有日历事件。恶意应用程序可能会将您的日历事件发送给其他人。'],
        'WRITE_CALENDAR': ['dangerous', '添加或修改日历事件并向客人发送电子邮件', '允许应用程序添加或更改您日历上的事件，这可能会向客人发送电子邮件。恶意应用程序可能会使用此权限删除或修改您的日历事件，或向客人发送电子邮件。'],
        'READ_USER_DICTIONARY': ['dangerous', '读取用户定义的字典', '允许应用程序读取用户可能已存储在用户字典中的任何私人单词、名称和短语。'],
        'WRITE_USER_DICTIONARY': ['normal', '写入用户定义的字典', '允许应用程序向用户字典写入新单词。'],
        'READ_HISTORY_BOOKMARKS': ['dangerous', '读取浏览器的历史记录和书签', '允许应用程序读取浏览器已访问的所有URL以及浏览器的所有书签。'],
        'WRITE_HISTORY_BOOKMARKS': ['dangerous', '写入浏览器的历史记录和书签', '允许应用程序修改存储在您手机上的浏览器历史记录或书签。恶意应用程序可能会使用此权限删除或修改您的浏览器数据。'],
        'SET_ALARM': ['normal', '在闹钟中设置闹铃', '允许应用程序在已安装的闹钟应用程序中设置闹铃。某些闹钟应用程序可能不实现此功能。'],
        'ACCESS_FINE_LOCATION': ['dangerous', '精确位置（GPS）', '访问精确位置信息源，如手机上的全球定位系统（GPS）（如果可用）。恶意应用程序可能会使用此权限确定您的位置，并可能消耗额外的电池电量。'],
        'ACCESS_COARSE_LOCATION': ['dangerous', '粗略位置（基于网络）', '访问粗略位置信息源，如移动网络数据库，以确定手机的大致位置（如果可用）。恶意应用程序可能会使用此权限大致确定您的位置。'],
        'ACCESS_MOCK_LOCATION': ['dangerous', '模拟位置源进行测试', '创建用于测试的模拟位置源。恶意应用程序可能会使用此权限覆盖GPS或网络提供商等真实位置源返回的位置和/或状态。'],
        'ACCESS_LOCATION_EXTRA_COMMANDS': ['normal', '访问额外的位置提供商命令', '访问额外的位置提供商命令。恶意应用程序可能会使用此权限干扰GPS或其他位置源的操作。'],
        'INSTALL_LOCATION_PROVIDER': ['signatureOrSystem', '安装位置提供商的权限', '创建用于测试的模拟位置源。恶意应用程序可能会使用此权限覆盖GPS或网络提供商等真实位置源返回的位置和/或状态，或监控并向外部源报告您的位置。'],
        'INTERNET': ['normal', '完全的互联网访问', '允许应用程序创建网络套接字。'],
        'ACCESS_NETWORK_STATE': ['normal', '查看网络状态', '允许应用程序查看所有网络的状态。'],
        'ACCESS_WIFI_STATE': ['normal', '查看Wi-Fi状态', '允许应用程序查看有关Wi-Fi状态的信息。'],
        'BLUETOOTH': ['normal', '创建蓝牙连接', '允许应用程序连接到已配对的蓝牙设备。'],
        'NFC': ['normal', '控制近场通信', '允许应用程序与近场通信（NFC）标签、卡片和读卡器通信。'],
        'USE_SIP': ['dangerous', '拨打/接听互联网电话', '允许应用程序使用SIP服务拨打/接听互联网电话。'],
        'ACCOUNT_MANAGER': ['signature', '作为账户管理器服务', '允许应用程序调用账户认证器。'],
        'GET_ACCOUNTS': ['dangerous', '列出账户', '允许访问账户服务中的账户列表。'],
        'AUTHENTICATE_ACCOUNTS': ['dangerous', '作为账户认证器', '允许应用程序使用账户管理器的账户认证功能，包括创建账户以及获取和设置其密码。'],
        'USE_CREDENTIALS': ['dangerous', '使用账户的认证凭据', '允许应用程序请求认证令牌。'],
        'MANAGE_ACCOUNTS': ['dangerous', '管理账户列表', '允许应用程序执行添加和删除账户以及删除其密码等操作。'],
        'MODIFY_AUDIO_SETTINGS': ['normal', '更改您的音频设置', '允许应用程序修改全局音频设置，如音量和路由。'],
        'RECORD_AUDIO': ['dangerous', '录制音频', '允许应用程序访问音频录制路径。'],
        'CAMERA': ['dangerous', '拍摄照片和视频', '允许应用程序使用相机拍摄照片和视频。这允许应用程序随时收集相机正在看到的图像。'],
        'VIBRATE': ['normal', '控制振动器', '允许应用程序控制振动器。'],
        'FLASHLIGHT': ['normal', '控制闪光灯', '允许应用程序控制闪光灯。'],
        'ACCESS_USB': ['signatureOrSystem', '访问USB设备', '允许应用程序访问USB设备。'],
        'HARDWARE_TEST': ['signature', '测试硬件', '允许应用程序控制各种外围设备以进行硬件测试。'],
        'PROCESS_OUTGOING_CALLS': ['dangerous', '拦截外拨电话', '允许应用程序处理外拨电话并更改要拨打的号码。恶意应用程序可能会监控、重定向或阻止外拨电话。'],
        'MODIFY_PHONE_STATE': ['signatureOrSystem', '修改电话状态', '允许应用程序控制设备的电话功能。具有此权限的应用程序可以切换网络，打开和关闭手机无线电等，而不会通知您。'],
        'READ_PHONE_STATE': ['dangerous', '读取电话状态和身份', '允许应用程序访问设备的电话功能。具有此权限的应用程序可以确定此电话的电话号码和序列号，是否有通话活动，该通话连接到的号码等。'],
        'WRITE_EXTERNAL_STORAGE': ['dangerous', '读取/修改/删除外部存储内容', '允许应用程序写入外部存储。'],
        'READ_EXTERNAL_STORAGE': ['dangerous', '读取外部存储内容', '允许应用程序从外部存储读取。'],
        'WRITE_SETTINGS': ['dangerous', '修改全局系统设置', '允许应用程序修改系统的设置数据。恶意应用程序可能会破坏您的系统配置。'],
        'WRITE_SECURE_SETTINGS': ['signatureOrSystem', '修改安全系统设置', '允许应用程序修改系统的安全设置数据。不适用于普通应用程序。'],
        'WRITE_GSERVICES': ['signatureOrSystem', '修改Google服务地图', '允许应用程序修改Google服务地图。不适用于普通应用程序。'],
        'EXPAND_STATUS_BAR': ['normal', '展开/折叠状态栏', '允许应用程序展开或折叠状态栏。'],
        'GET_TASKS': ['dangerous', '检索正在运行的应用程序', '允许应用程序检索有关当前和最近运行的任务的信息。可能允许恶意应用程序发现有关其他应用程序的私人信息。'],
        'REORDER_TASKS': ['normal', '重新排序正在运行的应用程序', '允许应用程序将任务移动到前台和后台。恶意应用程序可能会在没有您控制的情况下强制自己到前台。'],
        'CHANGE_CONFIGURATION': ['signatureOrSystem', '更改您的UI设置', '允许应用程序更改当前配置，如区域设置或整体字体大小。'],
        'RESTART_PACKAGES': ['normal', '终止后台进程', '允许应用程序终止其他应用程序的后台进程，即使内存不低。'],
        'KILL_BACKGROUND_PROCESSES': ['normal', '终止后台进程', '允许应用程序终止其他应用程序的后台进程，即使内存不低。'],
        'FORCE_STOP_PACKAGES': ['signature', '强制停止其他应用程序', '允许应用程序强制停止其他应用程序。'],
        'DUMP': ['signatureOrSystem', '检索系统内部状态', '允许应用程序检索系统的内部状态。恶意应用程序可能会检索各种私人和安全信息，这些信息通常不需要。'],
        'SYSTEM_ALERT_WINDOW': ['dangerous', '显示系统级警报', '允许应用程序显示系统警报窗口。恶意应用程序可能会接管手机的整个屏幕。'],
        'SET_ANIMATION_SCALE': ['dangerous', '修改全局动画速度', '允许应用程序随时更改全局动画速度（更快或更慢的动画）。'],
        'PERSISTENT_ACTIVITY': ['dangerous', '使应用程序始终运行', '允许应用程序使其部分持久化，以便系统不能将其用于其他应用程序。'],
        'GET_PACKAGE_SIZE': ['normal', '测量应用程序存储空间', '允许应用程序找出任何包使用的空间。'],
        'SET_PREFERRED_APPLICATIONS': ['signature', '设置首选应用程序', '允许应用程序修改您的首选应用程序。这可能允许恶意应用程序静默更改运行的应用程序，欺骗您现有的应用程序以从您那里收集私人数据。'],
        'RECEIVE_BOOT_COMPLETED': ['normal', '开机自动启动', '允许应用程序在系统完成启动后立即启动自己。这可能会使手机启动时间更长，并允许应用程序通过始终运行来减慢整体手机速度。'],
        'BROADCAST_STICKY': ['normal', '发送粘性广播', '允许应用程序发送粘性广播，这些广播在广播结束后仍然存在。恶意应用程序可能会通过使手机使用过多内存而使手机变慢或不稳定。'],
        'WAKE_LOCK': ['normal', '防止手机休眠', '允许应用程序防止手机进入睡眠状态。'],
        'SET_WALLPAPER': ['normal', '设置壁纸', '允许应用程序设置系统壁纸。'],
        'SET_WALLPAPER_HINTS': ['normal', '设置壁纸大小提示', '允许应用程序设置系统壁纸大小提示。'],
        'SET_TIME': ['signatureOrSystem', '设置时间', '允许应用程序更改手机的时钟时间。'],
        'SET_TIME_ZONE': ['signatureOrSystem', '设置时区', '允许应用程序更改手机的时区。'],
        'MOUNT_UNMOUNT_FILESYSTEMS': ['dangerous', '挂载和卸载文件系统', '允许应用程序挂载和卸载可移动存储的文件系统。'],
        'MOUNT_FORMAT_FILESYSTEMS': ['dangerous', '格式化外部存储', '允许应用程序格式化可移动存储。'],
        'ASEC_ACCESS': ['signature', '获取内部存储信息', '允许应用程序获取内部存储信息。'],
        'ASEC_CREATE': ['signature', '创建内部存储', '允许应用程序创建内部存储。'],
        'ASEC_DESTROY': ['signature', '销毁内部存储', '允许应用程序销毁内部存储。'],
        'ASEC_MOUNT_UNMOUNT': ['signature', '挂载/卸载内部存储', '允许应用程序挂载/卸载内部存储。'],
        'ASEC_RENAME': ['signature', '重命名内部存储', '允许应用程序重命名内部存储。'],
        'DISABLE_KEYGUARD': ['normal', '禁用键盘锁', '允许应用程序在不安全的情况下禁用键盘锁。'],
        'READ_SYNC_SETTINGS': ['normal', '读取同步设置', '允许应用程序读取同步设置，例如是否为联系人启用了同步。'],
        'WRITE_SYNC_SETTINGS': ['normal', '写入同步设置', '允许应用程序修改同步设置，例如是否为联系人启用了同步。'],
        'READ_SYNC_STATS': ['normal', '读取同步统计信息', '允许应用程序读取同步统计信息；例如，已发生的同步历史记录。'],
        'WRITE_APN_SETTINGS': ['dangerous', '写入接入点名称设置', '允许应用程序修改APN设置，如任何APN的代理和端口。'],
        'SUBSCRIBED_FEEDS_READ': ['normal', '读取订阅的源', '允许应用程序接收有关当前同步的源的详细信息。'],
        'SUBSCRIBED_FEEDS_WRITE': ['dangerous', '写入订阅的源', '允许应用程序修改您当前同步的源。这可能允许恶意应用程序更改您的同步源。'],
        'CHANGE_NETWORK_STATE': ['normal', '更改网络连接', '允许应用程序更改网络连接状态。'],
        'CHANGE_WIFI_STATE': ['normal', '更改Wi-Fi状态', '允许应用程序连接到Wi-Fi接入点并断开连接，以及对已配置的Wi-Fi网络进行更改。'],
        'CHANGE_WIFI_MULTICAST_STATE': ['normal', '允许Wi-Fi多播接收', '允许应用程序接收不直接发送到您设备的数据包。这在发现附近提供的服务时很有用。它比非多播模式使用更多的电量。'],
        'BLUETOOTH_ADMIN': ['normal', '蓝牙管理', '允许应用程序发现和配对蓝牙设备。'],
        'CLEAR_APP_CACHE': ['signatureOrSystem', '删除所有应用程序缓存数据', '允许应用程序通过删除应用程序缓存目录中的文件来释放手机存储空间。访问通常严格限制为系统进程。'],
        'READ_LOGS': ['dangerous', '读取敏感日志数据', '允许应用程序从系统的各种日志文件中读取。这使其能够发现您使用手机的一般信息，可能包括个人或私人信息。'],
        'SET_DEBUG_APP': ['dangerous', '启用应用程序调试', '允许应用程序为另一个应用程序打开调试。恶意应用程序可能会使用此权限杀死其他应用程序。'],
        'SET_PROCESS_LIMIT': ['dangerous', '限制运行进程的数量', '允许应用程序控制将运行的最大进程数。普通应用程序从不需要。'],
        'SET_ALWAYS_FINISH': ['dangerous', '使所有后台应用程序关闭', '允许应用程序控制活动是否在进入后台后立即完成。普通应用程序从不需要。'],
        'SIGNAL_PERSISTENT_PROCESSES': ['dangerous', '向应用程序发送Linux信号', '允许应用程序请求将提供的信号发送到所有持久进程。'],
        'DIAGNOSTIC': ['signature', '读取/写入诊断组拥有的资源', '允许应用程序读取和写入诊断组拥有的任何资源；例如，/dev中的文件。这可能会影响系统稳定性和安全性。这应该仅用于制造商或运营商的特定于硬件的诊断。'],
        'STATUS_BAR': ['signatureOrSystem', '禁用或修改状态栏', '允许应用程序禁用状态栏或添加和删除系统图标。'],
        'STATUS_BAR_SERVICE': ['signature', '状态栏', '允许应用程序成为状态栏。'],
        'FORCE_BACK': ['signature', '强制应用程序关闭', '允许应用程序强制任何在前台的活动关闭并返回。普通应用程序从不需要。'],
        'UPDATE_DEVICE_STATS': ['signatureOrSystem', '修改电池统计信息', '允许修改收集的电池统计信息。不适用于普通应用程序。'],
        'INTERNAL_SYSTEM_WINDOW': ['signature', '显示未授权的窗口', '允许创建旨在由内部系统用户界面使用的窗口。不适用于普通应用程序。'],
        'MANAGE_APP_TOKENS': ['signature', '管理应用程序令牌', '允许应用程序创建和管理自己的令牌，绕过它们的常见Z排序。普通应用程序从不需要。'],
        'INJECT_EVENTS': ['signature', '按键和控制按钮', '允许应用程序将自己的输入事件（按键等）传递给其他应用程序。恶意应用程序可能会使用此权限完全控制手机。'],
        'SET_ACTIVITY_WATCHER': ['signature', '监控和控制所有应用程序启动', '允许应用程序监控和控制系统如何启动活动。恶意应用程序可能会完全破坏系统。此权限仅用于开发，从不用于普通手机使用。'],
        'SHUTDOWN': ['signature', '部分关机', '将活动管理器置于关机状态。不执行完全关机。'],
        'STOP_APP_SWITCHES': ['signature', '防止应用程序切换', '防止用户切换到另一个应用程序。'],
        'READ_INPUT_STATE': ['signature', '记录您键入的内容和您采取的操作', '允许应用程序观察您按下的键，即使在与另一个应用程序交互时（例如输入密码）。普通应用程序从不需要。'],
        'BIND_INPUT_METHOD': ['signature', '绑定到输入法', '允许持有者绑定到输入法的顶级接口。普通应用程序从不需要。'],
        'BIND_WALLPAPER': ['signatureOrSystem', '绑定到壁纸', '允许持有者绑定到壁纸的顶级接口。普通应用程序从不需要。'],
        'BIND_DEVICE_ADMIN': ['signature', '与设备管理员交互', '允许持有者向设备管理员发送意图。普通应用程序从不需要。'],
        'SET_ORIENTATION': ['signature', '更改屏幕方向', '允许应用程序随时更改屏幕的旋转。普通应用程序从不需要。'],
        'INSTALL_PACKAGES': ['signatureOrSystem', '直接安装应用程序', '允许应用程序安装新的或更新的Android软件包。恶意应用程序可能会使用此权限添加具有任意强大权限的新应用程序。'],
        'REQUEST_INSTALL_PACKAGES': ['dangerous', '允许应用程序请求安装软件包', '恶意应用程序可能会使用此权限尝试诱使用户安装额外的恶意软件包。'],
        'CLEAR_APP_USER_DATA': ['signature', '删除其他应用程序的数据', '允许应用程序清除用户数据。'],
        'DELETE_CACHE_FILES': ['signatureOrSystem', '删除其他应用程序的缓存', '允许应用程序删除缓存文件。'],
        'DELETE_PACKAGES': ['signatureOrSystem', '删除应用程序', '允许应用程序删除Android软件包。恶意应用程序可能会使用此权限删除重要的应用程序。'],
        'MOVE_PACKAGE': ['signatureOrSystem', '移动应用程序资源', '允许应用程序将应用程序资源从内部移动到外部媒体，反之亦然。'],
        'CHANGE_COMPONENT_ENABLED_STATE': ['signatureOrSystem', '启用或禁用应用程序组件', '允许应用程序更改另一个应用程序的组件是否启用。恶意应用程序可能会使用此权限禁用重要的手机功能。使用此权限时必须小心，因为可能会使应用程序组件处于不可用、不一致或不稳定的状态。'],
        'ACCESS_SURFACE_FLINGER': ['signature', '访问SurfaceFlinger', '允许应用程序使用SurfaceFlinger低级功能。'],
        'READ_FRAME_BUFFER': ['signature', '读取帧缓冲区', '允许应用程序读取帧缓冲区的内容。'],
        'BRICK': ['signature', '永久禁用手机', '允许应用程序永久禁用整个手机。这非常危险。'],
        'REBOOT': ['signatureOrSystem', '强制手机重启', '允许应用程序强制手机重启。'],
        'DEVICE_POWER': ['signature', '打开或关闭手机', '允许应用程序打开或关闭手机。'],
        'FACTORY_TEST': ['signature', '在工厂测试模式下运行', '作为低级制造商测试运行，允许完全访问手机硬件。仅在手机以制造商测试模式运行时可用。'],
        'BROADCAST_PACKAGE_REMOVED': ['signature', '发送包已删除广播', '允许应用程序广播应用程序包已被删除的通知。恶意应用程序可能会使用此权限杀死任何其他正在运行的应用程序。'],
        'BROADCAST_SMS': ['signature', '发送短信接收广播', '允许应用程序广播已接收短信的通知。恶意应用程序可能会使用此权限伪造传入的短信。'],
        'BROADCAST_WAP_PUSH': ['signature', '发送WAP-PUSH接收广播', '允许应用程序广播已接收WAP-PUSH消息的通知。恶意应用程序可能会使用此权限伪造彩信接收或静默替换任何网页的内容为恶意变体。'],
        'MASTER_CLEAR': ['signatureOrSystem', '将系统重置为出厂默认设置', '允许应用程序将系统完全重置为出厂设置，擦除所有数据、配置和已安装的应用程序。'],
        'CALL_PRIVILEGED': ['signatureOrSystem', '直接拨打任何电话号码', '允许应用程序在没有您干预的情况下拨打任何电话号码，包括紧急号码。恶意应用程序可能会向紧急服务机构拨打不必要和非法的电话。'],
        'PERFORM_CDMA_PROVISIONING': ['signatureOrSystem', '直接启动CDMA电话设置', '允许应用程序启动CDMA配置。恶意应用程序可能会不必要地启动CDMA配置。'],
        'CONTROL_LOCATION_UPDATES': ['signatureOrSystem', '控制位置更新通知', '允许启用/禁用来自无线电的位置更新通知。不适用于普通应用程序。'],
        'ACCESS_CHECKIN_PROPERTIES': ['signatureOrSystem', '访问签入属性', '允许读/写访问由签入服务上传的属性。不适用于普通应用程序。'],
        'PACKAGE_USAGE_STATS': ['signature', '更新组件使用统计信息', '允许修改收集的组件使用统计信息。不适用于普通应用程序。'],
        'BATTERY_STATS': ['signature', '修改电池统计信息', '允许修改收集的电池统计信息。不适用于普通应用程序。'],
        'BACKUP': ['signatureOrSystem', '控制系统备份和恢复', '允许应用程序控制系统的备份和恢复机制。不适用于普通应用程序。'],
        'BIND_APPWIDGET': ['signatureOrSystem', '选择小部件', '允许应用程序告诉系统哪些小部件可以被哪个应用程序使用。使用此权限，应用程序可以将个人数据访问权授予其他应用程序。不适用于普通应用程序。'],
        'CHANGE_BACKGROUND_DATA_SETTING': ['signature', '更改后台数据使用设置', '允许应用程序更改后台数据使用设置。'],
        # 短描述由ChatGPT生成，可能不准确
        'GLOBAL_SEARCH': ['signatureOrSystem', "允许全局搜索系统访问提供者的数据。", '此权限可用于内容提供者，以允许全局搜索系统访问其数据。通常在提供者有一些权限保护它（全局搜索不会被期望持有）时使用，并作为只读权限添加到提供者中执行全局搜索查询的路径。普通应用程序不能持有此权限；它仅供应用程序用于保护自己免受除全局搜索之外的所有人的影响。'],
        'GLOBAL_SEARCH_CONTROL': ['signature', '未指定角色或功能的权限。', '未指定角色或功能的权限。'],
        'SET_WALLPAPER_COMPONENT': ['signatureOrSystem', '允许设置壁纸组件。', '允许设置壁纸组件。'],
        'ACCESS_CACHE_FILESYSTEM': ['signatureOrSystem', '访问缓存文件系统', '允许应用程序读取和写入缓存文件系统。'],
        'COPY_PROTECTED_DATA': ['signature', '允许调用默认容器服务来复制内容。不适用于普通应用程序。', '允许调用默认容器服务来复制内容。不适用于普通应用程序。'],
        'C2D_MESSAGE': ['signature', '允许云到设备的消息传递', '允许应用程序接收推送通知。'],
        'ADD_VOICEMAIL': ['dangerous', '将语音邮件添加到系统中', '允许应用程序将语音邮件添加到系统中。'],
        'ACCEPT_HANDOVER': ['dangerous', '使呼叫应用能够继续在另一个应用中开始的呼叫。', "允许呼叫应用继续在另一个应用中开始的呼叫。例如，视频通话应用想要继续用户移动网络上的语音通话。"],
        'ACCESS_NOTIFICATION_POLICY': ['normal', '访问通知策略的标记权限。', '希望访问通知策略的应用程序的标记权限。'],
        'ANSWER_PHONE_CALLS': ['dangerous', '允许应用接听来电。', '允许应用接听来电。'],
        'BIND_ACCESSIBILITY_SERVICE': ['signature', 'AccessibilityServices需要系统绑定的必要权限。', '必须由AccessibilityService要求，以确保只有系统可以绑定到它。'],
        'BIND_AUTOFILL_SERVICE': ['signature', 'AutofillServices需要系统绑定的必要权限。', '必须由AutofillService要求，以确保只有系统可以绑定到它。'],
        'BIND_CARRIER_MESSAGING_SERVICE': ['signature', '绑定到运营商消息服务的系统级权限。', '允许系统进程绑定到运营商应用中的服务。'],
        'BIND_CARRIER_SERVICES': ['signature', '绑定到运营商服务的系统级权限。', '允许系统进程绑定到运营商应用中的服务。运营商应用应使用此权限保护其服务，以便只有系统才能绑定到它们。'],
        'BIND_CHOOSER_TARGET_SERVICE': ['signature', 'ChooserTargetServices需要系统绑定的必要权限。', '必须由ChooserTargetService要求，以确保只有系统可以绑定到它。'],
        'BIND_CONDITION_PROVIDER_SERVICE': ['signature', 'ConditionProviderServices需要系统绑定的必要权限。', '必须由ConditionProviderService要求，以确保只有系统可以绑定到它。'],
        'BIND_DREAM_SERVICE': ['signature', 'DreamServices需要系统绑定的必要权限。', '必须由DreamService要求，以确保只有系统可以绑定到它。'],
        'BIND_INCALL_SERVICE': ['signature', 'InCallServices需要系统绑定的必要权限。', '必须由InCallService要求，以确保只有系统可以绑定到它。'],
        'BIND_MIDI_DEVICE_SERVICE': ['signature', 'MidiDeviceServices需要系统绑定的必要权限。', '必须由MidiDeviceService要求，以确保只有系统可以绑定到它。'],
        'BIND_NFC_SERVICE': ['signature', '系统绑定到NFC服务所需的权限。', '必须由HostApduService或OffHostApduService要求，以确保只有系统可以绑定到它。'],
        'BIND_NOTIFICATION_LISTENER_SERVICE': ['signature', 'NotificationListenerServices需要系统绑定的必要权限。', '必须由NotificationListenerService要求，以确保只有系统可以绑定到它。'],
        'BIND_PRINT_SERVICE': ['signature', 'PrintServices需要系统绑定的必要权限。', '必须由PrintService要求，以确保只有系统可以绑定到它。'],
        'BIND_QUICK_SETTINGS_TILE': ['signatureOrSystem', '允许绑定到第三方快速设置磁贴。', '允许应用程序绑定到第三方快速设置磁贴。'],
        'BIND_REMOTEVIEWS': ['signature', 'RemoteViewsServices需要系统绑定的必要权限。', '必须由RemoteViewsService要求，以确保只有系统可以绑定到它。'],
        'BIND_SCREENING_SERVICE': ['signature', 'CallScreeningServices需要系统绑定的必要权限。', '必须由CallScreeningService要求，以确保只有系统可以绑定到它。'],
        'BIND_TELECOM_CONNECTION_SERVICE': ['signature', 'ConnectionServices需要系统绑定的必要权限。', '必须由ConnectionService要求，以确保只有系统可以绑定到它。'],
        'BIND_TEXT_SERVICE': ['signature', 'TextServices（例如，SpellCheckerService）需要系统绑定的必要权限。', '必须由TextService（例如SpellCheckerService）要求，以确保只有系统可以绑定到它。'],
        'BIND_TV_INPUT': ['signature', 'TvInputServices需要系统绑定的必要权限。', '必须由TvInputService要求，以确保只有系统可以绑定到它。'],
        'BIND_VISUAL_VOICEMAIL_SERVICE': ['signature', 'VisualVoicemailServices需要系统绑定的必要权限。', '必须由VisualVoicemailService要求，以确保只有系统可以绑定到它。'],
        'BIND_VOICE_INTERACTION': ['signature', 'VoiceInteractionServices需要系统绑定的必要权限。', '必须由VoiceInteractionService要求，以确保只有系统可以绑定到它。'],
        'BIND_VPN_SERVICE': ['signature', 'VpnServices需要系统绑定的必要权限。', '必须由VpnService要求，以确保只有系统可以绑定到它。'],
        'BIND_VR_LISTENER_SERVICE': ['signature', 'VrListenerServices需要系统绑定的必要权限。', '必须由VrListenerService要求，以确保只有系统可以绑定到它。'],
        'BLUETOOTH_PRIVILEGED': ['signatureOrSystem', '允许在没有用户交互的情况下执行特权蓝牙操作。', '允许应用程序在没有用户交互的情况下配对蓝牙设备，以及允许或禁止电话簿访问或消息访问。第三方应用程序无法使用此权限。'],
        'BODY_SENSORS': ['dangerous', '授予访问身体传感器的权限，如心率。', '允许应用程序访问用户用来测量身体内部情况的传感器数据，如心率。'],
        'CAPTURE_AUDIO_OUTPUT': ['signatureOrSystem', '允许捕获音频输出。', '允许应用程序捕获音频输出。'],
        'CAPTURE_SECURE_VIDEO_OUTPUT': ['normal', '允许捕获安全视频输出。', '允许应用程序捕获安全视频输出。'],
        'CAPTURE_VIDEO_OUTPUT': ['normal', '允许捕获视频输出。', '允许应用程序捕获视频输出。'],
        'FOREGROUND_SERVICE': ['normal', '使普通应用能够使用Service.startForeground。', '允许普通应用程序使用Service.startForeground。'],
        'GET_ACCOUNTS_PRIVILEGED': ['signatureOrSystem', '授予对账户服务的访问权限。', '允许访问账户服务中的账户列表。'],
        'INSTALL_SHORTCUT': ['normal', '允许在启动器中安装快捷方式。', '允许应用程序在启动器中安装快捷方式。'],
        'INSTANT_APP_FOREGROUND_SERVICE': ['signatureOrSystem', '允许即时应用创建前台服务。', '允许即时应用创建前台服务。'],
        'LOCATION_HARDWARE': ['normal', '允许使用硬件中的位置功能。', '允许应用程序使用硬件中的位置功能，如地理围栏API。'],
        'MANAGE_DOCUMENTS': ['signature', '允许管理文档访问，通常在选择器中。', '允许应用程序管理对文档的访问，通常作为文档选择器的一部分。'],
        'MANAGE_OWN_CALLS': ['normal', '使呼叫应用能够管理自己的呼叫。', '允许通过自管理的ConnectionService API管理自己呼叫的呼叫应用程序。'],
        'MEDIA_CONTENT_CONTROL': ['normal', '允许控制媒体内容播放。', '允许应用程序知道正在播放什么内容并控制其播放。'],
        'NFC_TRANSACTION_EVENT': ['normal', '允许接收NFC交易事件。', '允许应用程序接收NFC交易事件。'],
        'READ_CALL_LOG': ['dangerous', "授予对用户通话记录的读取访问权限。", "允许应用程序读取用户的通话记录。"],
        'READ_PHONE_NUMBERS': ['dangerous', "允许读取设备的电话号码。", "允许读取设备的电话号码。这是READ_PHONE_STATE授予的功能的子集，但对即时应用程序公开。"],
        'READ_VOICEMAIL': ['signature', '允许应用程序读取系统中的语音邮件。', '允许应用程序读取系统中的语音邮件。'],
        'REQUEST_COMPANION_RUN_IN_BACKGROUND': ['normal', '允许伴侣应用在后台运行。', '允许伴侣应用在后台运行。'],
        'REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': ['normal', '允许伴侣应用在后台使用数据。', '允许伴侣应用在后台使用数据。'],
        'REQUEST_DELETE_PACKAGES': ['normal', '使应用能够请求删除软件包。', '允许应用程序请求删除软件包。'],
        'REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': ['normal', '使用Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS的权限。', '应用程序必须持有此权限才能使用Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS。'],
        'SEND_RESPOND_VIA_MESSAGE': ['signatureOrSystem', '允许在通话期间发送响应消息请求。', '允许应用程序（电话）在来电期间向其他应用程序发送请求，以处理通过消息响应操作。'],
        'TRANSMIT_IR': ['normal', "允许使用设备的红外发射器。", "允许使用设备的红外发射器（如果可用）。"],
        'UNINSTALL_SHORTCUT': ['normal', '卸载快捷方式的已弃用权限。', "不要在您的应用中使用此权限。此权限不再受支持。"],
        'USE_BIOMETRIC': ['normal', '允许使用设备支持的生物识别模式。', '允许应用程序使用设备支持的生物识别模式。'],
        'USE_FINGERPRINT': ['normal', '允许使用指纹', '此常量在API级别28中已弃用。应用程序应该请求USE_BIOMETRIC。'],
        'WRITE_CALL_LOG': ['dangerous', "允许写入（但不读取）用户的通话记录。", "允许应用程序写入（但不读取）用户的通话记录数据。"],
        'WRITE_VOICEMAIL': ['signature', '允许修改和删除语音邮件。', '允许应用程序修改和删除系统中的现有语音邮件。'],
        'ACCESS_BACKGROUND_LOCATION': ['dangerous', '在后台访问位置', '允许应用程序在后台访问位置。'],
        'ACCESS_MEDIA_LOCATION': ['dangerous', '访问任何地理位置', "允许应用程序访问用户共享集合中保存的任何地理位置。"],
        'ACTIVITY_RECOGNITION': ['dangerous', '允许应用程序识别身体活动', '允许应用程序识别身体活动。'],
        'BIND_CALL_REDIRECTION_SERVICE': ['signature', 'CallRedirectionServices需要系统绑定的必要权限。', '必须由CallRedirectionService要求，以确保只有系统可以绑定到它。'],
        'BIND_CARRIER_MESSAGING_CLIENT_SERVICE': ['signature', 'CarrierMessagingClientServices需要系统保护的必要权限。', 'CarrierMessagingClientService的子类必须受此权限保护。'],
        'CALL_COMPANION_APP': ['normal', '使InCallService应用能够作为呼叫伴侣应用功能。', "允许实现InCallService API的应用有资格被启用为呼叫伴侣应用。这意味着当有活动呼叫时，Telecom框架将绑定到应用的InCallService实现。应用可以使用InCallService API查看系统上的呼叫信息并控制这些呼叫。"],
        'REQUEST_PASSWORD_COMPLEXITY': ['normal', '允许请求和提示屏幕锁定复杂性升级。', '允许应用程序请求屏幕锁定复杂性并提示用户将屏幕锁定更新到特定的复杂性级别。'],
        'SMS_FINANCIAL_TRANSACTIONS': ['signature', '允许金融应用读取过滤的短信消息', '允许金融应用读取过滤的短信消息。保护级别：signature|appop。此常量在API级别S中已弃用。'],
        'START_VIEW_PERMISSION_USAGE': ['signature', '允许启动应用的权限使用屏幕。', '允许持有者启动应用的权限使用屏幕。'],
        'USE_FULL_SCREEN_INTENT': ['normal', '通知中全屏意图所需的权限。', '针对Build.VERSION_CODES.Q的应用程序如果想要使用通知全屏意图，则需要此权限。'],
        'ACCESS_CALL_AUDIO': ['signature', '应用程序可以访问通话音频', '允许分配给拨号器角色的应用程序被授予访问电话通话音频流的权限，包括TX和RX。'],
        'BIND_CONTROLS': ['signatureOrSystem', '允许SystemUI请求第三方控件。', '允许SystemUI请求第三方控件。应该只由系统请求，并由ControlsProviderService声明所需。'],
        'BIND_QUICK_ACCESS_WALLET_SERVICE': ['signature', 'QuickAccessWalletServices需要系统绑定的必要权限。', '必须由QuickAccessWalletService要求，以确保只有系统可以绑定到它。'],
        'INTERACT_ACROSS_PROFILES': ['normal', '使同一组中的配置文件之间能够交互。', '允许同一配置文件组中的配置文件之间交互。'],
        'LOADER_USAGE_STATS': ['signatureOrSystem', '允许数据加载器读取包访问日志。', "允许数据加载器读取包的访问日志。访问日志包含随时间引用的页面集。"],
        'MANAGE_EXTERNAL_STORAGE': ['dangerous', '允许应用程序在范围存储中广泛访问外部存储', '允许应用程序在范围存储中广泛访问外部存储。旨在供少数需要代表用户管理文件的应用使用。'],
        'NFC_PREFERRED_PAYMENT_INFO': ['normal', '允许接收NFC首选支付服务信息。', '允许应用程序接收NFC首选支付服务信息。'],
        'QUERY_ALL_PACKAGES': ['normal', '使能够查询设备上的任何普通应用。', '允许查询设备上的任何普通应用，无论清单声明如何。'],
        'READ_PRECISE_PHONE_STATE': ['dangerous', '允许只读访问精确的电话状态。', '允许只读访问精确的电话状态。允许读取有关电话状态的详细信息，供特殊用途的应用程序使用，如拨号器、运营商应用程序或ims应用程序。'],
        'READ_APP_BADGE': ['normal', '显示应用通知', '允许应用程序显示应用图标徽章。'],
        'BIND_COMPANION_DEVICE_SERVICE': ['normal', 'CompanionDeviceServices需要系统绑定的必要权限。', '任何CompanionDeviceServices必须要求此权限，以确保只有系统可以绑定到它。'],
        'HIDE_OVERLAY_WINDOWS': ['normal', '防止非系统覆盖窗口 ', '允许应用程序防止非系统覆盖窗口在其上方绘制。'],
        'HIGH_SAMPLING_RATE_SENSORS': ['normal', '访问更高采样率的传感器数据', '允许应用程序访问采样率大于200 Hz的传感器数据。'],
        'MANAGE_ONGOING_CALLS': ['signature', '查询和管理正在进行的通话详情', '允许查询正在进行的通话详情并管理正在进行的通话。'],
        'REQUEST_COMPANION_PROFILE_WATCH': ['normal', "使能够将设备关联为'手表'。", '允许应用程序通过CompanionDeviceManager请求与设备关联为"手表"。'],
        'REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE': ['normal', '允许订阅伴侣设备存在状态通知。', '允许应用程序订阅关于其关联的伴侣设备存在状态变化的通知。'],
        'SCHEDULE_EXACT_ALARM': ['normal', '允许为后台工作安排精确的闹钟。', '允许应用程序使用精确的闹钟调度API执行时间敏感的后台工作。'],
        'USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER': ['signature', '允许读取设备标识符并使用基于ICC的认证。', "允许读取设备标识符并使用基于ICC的认证，如EAP-AKA。在认证以访问运营商的服务器和管理订户的服务时通常需要。"],
        'ACCESS_BLOBS_ACROSS_USERS': ['normal', '使能够跨用户访问数据块。', '允许应用程序跨用户访问数据块。'],
        'BIND_CREDENTIAL_PROVIDER_SERVICE': ['signature', 'CredentialProviderServices需要系统绑定的必要权限。', '必须由CredentialProviderService要求，以确保只有系统可以绑定到它。'],
        'BIND_TV_INTERACTIVE_APP': ['signature', 'TvInteractiveAppServices需要系统绑定的必要权限。', '必须由TvInteractiveAppService要求，以确保只有系统可以绑定到它。'],
        'BLUETOOTH_ADVERTISE': ['dangerous', '向附近的蓝牙设备广播所需的权限。', '能够向附近的蓝牙设备广播所需的权限。'],
        'BLUETOOTH_CONNECT': ['dangerous', '连接到已配对的蓝牙设备所必需的权限。', '能够连接到已配对的蓝牙设备所需的权限。'],
        'BLUETOOTH_SCAN': ['dangerous', '发现和配对蓝牙设备所需的权限。', '能够发现和配对附近的蓝牙设备所需的权限。'],
        'BODY_SENSORS_BACKGROUND': ['dangerous', '授予对身体传感器的后台访问权限，如心率。', "允许应用程序访问用户用来测量身体内部情况的传感器数据，如心率。如果您请求此权限，您还必须请求BODY_SENSORS。仅请求此权限本身不会授予您身体传感器访问权限。"],
        'CONFIGURE_WIFI_DISPLAY': ['normal', '允许配置和连接到Wifi显示器。', '允许应用程序配置和连接到Wifi显示器'],
        'CREDENTIAL_MANAGER_QUERY_CANDIDATE_CREDENTIALS': ['normal', '使能够查询凭据候选者的元数据。', '允许浏览器调用一组查询API，以获取在CredentialManager.prepareGetCredential API期间准备的凭据候选者的元数据。'],
        'CREDENTIAL_MANAGER_SET_ALLOWED_PROVIDERS': ['normal', '允许指定候选凭据提供者。', '允许指定在凭据管理器获取流程中要查询的候选凭据提供者，或在凭据管理器创建流程中作为默认首选项。'],
        'CREDENTIAL_MANAGER_SET_ORIGIN': ['normal', '使能够代表另一个RP使用凭据管理器API。', '允许浏览器代表另一个RP调用凭据管理器API。'],
        'DELIVER_COMPANION_MESSAGES': ['normal', '允许向系统传递伴侣消息。', '允许应用程序向系统传递伴侣消息'],
        'DETECT_SCREEN_CAPTURE': ['normal', "当尝试捕获应用窗口的屏幕截图时通知。", '允许应用程序在尝试捕获其窗口的屏幕截图时得到通知。'],
        'ENFORCE_UPDATE_OWNERSHIP': ['normal', '表示通过PackageInstaller成为更新所有者的意图。', '允许应用程序通过PackageInstaller.SessionParams.setRequestUpdateOwnership(boolean)表明它有意成为更新所有者。'],
        'EXECUTE_APP_ACTION': ['internal', '允许辅助应用在其他应用内执行操作。', '允许辅助应用程序代表用户在应用程序内执行操作。'],
        'FOREGROUND_SERVICE_CAMERA': ['normal', '允许使用相机的前台服务。', '允许普通应用程序使用类型为"camera"的Service.startForeground。'],
        'FOREGROUND_SERVICE_CONNECTED_DEVICE': ['normal', '使能够使用连接设备的前台服务。', '允许普通应用程序使用类型为"connectedDevice"的Service.startForeground。'],
        'FOREGROUND_SERVICE_DATA_SYNC': ['normal', '允许用于数据同步的前台服务。', '允许普通应用程序使用类型为"dataSync"的Service.startForeground。'],
        'FOREGROUND_SERVICE_HEALTH': ['normal', '使能够使用与健康相关功能的前台服务。', '允许普通应用程序使用类型为"health"的Service.startForeground。'],
        'FOREGROUND_SERVICE_LOCATION': ['normal', '允许使用位置的前台服务。', '允许普通应用程序使用类型为"location"的Service.startForeground。'],
        'FOREGROUND_SERVICE_MEDIA_PLAYBACK': ['normal', '使能够用于媒体播放的前台服务。', '允许普通应用程序使用类型为"mediaPlayback"的Service.startForeground。'],
        'FOREGROUND_SERVICE_MEDIA_PROJECTION': ['normal', '允许用于媒体投影的前台服务。', '允许普通应用程序使用类型为"mediaProjection"的Service.startForeground。'],
        'FOREGROUND_SERVICE_MICROPHONE': ['normal', '允许使用麦克风的前台服务。', '允许普通应用程序使用类型为"microphone"的Service.startForeground。'],
        'FOREGROUND_SERVICE_PHONE_CALL': ['normal', '使能够在电话通话期间使用前台服务。', '允许普通应用程序使用类型为"phoneCall"的Service.startForeground。'],
        'FOREGROUND_SERVICE_REMOTE_MESSAGING': ['normal', '允许用于远程消息传递的前台服务。', '允许普通应用程序使用类型为"remoteMessaging"的Service.startForeground。'],
        'FOREGROUND_SERVICE_SPECIAL_USE': ['normal', '使能够使用特殊用途的前台服务。', '允许普通应用程序使用类型为"specialUse"的Service.startForeground。'],
        'FOREGROUND_SERVICE_SYSTEM_EXEMPTED': ['normal', '允许系统豁免类型的前台服务。', '允许普通应用程序使用类型为"systemExempted"的Service.startForeground。应用程序只允许在ServiceInfo.FOREGROUND_SERVICE_TYPE_SYSTEM_EXEMPTED中列出的用例中使用此类型。'],
        'LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE': ['internal', '使能够捕获屏幕内容进行截图。', '允许应用程序使用意图操作Intent.ACTION_LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE捕获屏幕内容以执行截图。'],
        'LAUNCH_MULTI_PANE_SETTINGS_DEEP_LINK': ['normal', '使能够在设置应用中嵌入显示活动。', '应用程序需要此权限才能使用Settings.ACTION_SETTINGS_EMBED_DEEP_LINK_ACTIVITY在设置应用中嵌入显示其活动。'],
        'MANAGE_DEVICE_LOCK_STATE': ['internal', '允许金融设备信息亭应用与设备锁服务交互。', '允许金融设备信息亭应用在设备锁服务上执行操作'],
        'MANAGE_DEVICE_POLICY_ACCESSIBILITY': ['normal', '使能够管理与辅助功能相关的策略。', '允许应用程序管理与辅助功能相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_ACCOUNT_MANAGEMENT': ['normal', '允许设置与账户管理相关的策略。', '允许应用程序设置与账户管理相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS': ['normal', '使能够设置不访问用户数据的安全设备策略。', '允许应用程序设置当前用户之外的设备策略，这些策略是保护设备所有权所必需的，而不访问用户数据。持有此权限允许在设备上的所有用户上使用其他持有的MANAGE_DEVICE_POLICY_*权限，前提是它们不授予对用户数据的访问权限。'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL': ['normal', '允许设置可访问用户数据的设备策略。', '允许应用程序设置当前用户之外的设备策略。MANAGE_DEVICE_POLICY_ACROSS_USERS的更完整形式，消除了对访问用户数据的限制。持有此权限允许在设备上的所有用户上使用任何其他持有的MANAGE_DEVICE_POLICY_*权限。常量值："android.permission.MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL"'],
        'MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL': ['normal', '使能够设置保护当前用户数据的关键安全策略。', '允许应用程序设置当前用户之外的设备策略，这些策略对于保护当前用户内的数据至关重要。持有此权限允许在设备上的所有用户上使用其他持有的MANAGE_DEVICE_POLICY_*权限，前提是它们是保护当前用户内数据所必需的。'],
        'MANAGE_DEVICE_POLICY_AIRPLANE_MODE': ['normal', '允许设置与飞行模式相关的策略。', '允许应用程序设置与飞行模式相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_APPS_CONTROL': ['normal', '允许管理修改应用程序的策略。', '允许应用程序管理关于修改应用程序的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_APP_RESTRICTIONS': ['normal', '使能够管理应用程序限制。', '允许应用程序管理应用程序限制。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_APP_USER_DATA': ['normal', '允许设置应用程序用户数据的策略。', '允许应用程序管理与应用程序用户数据相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_AUDIO_OUTPUT': ['normal', '使能够设置音频输出的策略。', '允许应用程序设置与音频输出相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_AUTOFILL': ['normal', '允许设置自动填充服务的策略。', '允许应用程序设置与自动填充相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_BACKUP_SERVICE': ['normal', '使能够管理备份服务策略。', '允许应用程序管理备份服务策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_BLUETOOTH': ['normal', '允许设置与蓝牙相关的策略。', '允许应用程序设置与蓝牙相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_BUGREPORT': ['normal', '允许在用户同意的情况下请求错误报告。', '允许应用程序在用户同意的情况下请求错误报告。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_CALLS': ['normal', '使能够管理电话通话的策略。', '允许应用程序管理通话策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_CAMERA': ['normal', '允许设置相机使用的策略。', "允许应用程序设置与限制用户使用或启用和禁用相机的能力相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。"],
        'MANAGE_DEVICE_POLICY_CERTIFICATES': ['normal', '允许证书的策略管理。', '允许应用程序设置与证书相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_COMMON_CRITERIA_MODE': ['normal', '使能够管理通用标准模式的策略。', '允许应用程序管理与通用标准模式相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_DEBUGGING_FEATURES': ['normal', '允许管理调试功能的策略。', '允许应用程序管理调试功能策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_DEFAULT_SMS': ['normal', '允许设置默认短信应用程序的策略。', '允许应用程序设置与默认短信应用程序相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_DEVICE_IDENTIFIERS': ['normal', '使能够管理设备标识符的策略。', '允许应用程序管理与设备标识符相关的策略。'],
        'MANAGE_DEVICE_POLICY_DISPLAY': ['normal', '允许设置显示管理的策略。', '允许应用程序设置与显示相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_FACTORY_RESET': ['normal', '使能够设置工厂重置的策略。', '允许应用程序设置与工厂重置相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_FUN': ['normal', '允许设置与娱乐活动相关的策略。', '允许应用程序设置与娱乐相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_INPUT_METHODS': ['normal', '允许设置输入法的策略。', '允许应用程序设置与输入法相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_INSTALL_UNKNOWN_SOURCES': ['normal', '使能够设置从未知来源安装应用程序的策略。', '允许应用程序管理从未知来源安装的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要MANAGE_SECURITY_CRITICAL_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_KEEP_UNINSTALLED_PACKAGES': ['normal', '允许根据策略保留已卸载的软件包。', '允许应用程序设置与保留已卸载软件包相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_KEYGUARD': ['normal', '使能够管理键盘锁设置的策略。', '允许应用程序管理与键盘锁相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL。'],
        'MANAGE_DEVICE_POLICY_LOCALE': ['normal', '允许设置区域设置管理的策略。', '允许应用程序设置与区域设置相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_LOCATION': ['normal', '使能够设置位置服务的策略。', '允许应用程序设置与位置相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_LOCK': ['normal', '允许根据策略锁定配置文件或设备。', '允许应用程序使用适当的跨用户权限锁定配置文件或设备。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_LOCK_CREDENTIALS': ['normal', '使能够设置锁定凭据的策略。', '允许应用程序设置与锁定凭据相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL。'],
        'MANAGE_DEVICE_POLICY_LOCK_TASK': ['normal', '允许管理锁定任务策略。', '允许应用程序管理锁定任务策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_METERED_DATA': ['normal', '允许计量数据的策略管理。', '允许应用程序管理与计量数据相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_MICROPHONE': ['normal', '允许设置麦克风使用的策略。', "允许应用程序设置与限制用户使用或启用和禁用麦克风的能力相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。"],
        'MANAGE_DEVICE_POLICY_MOBILE_NETWORK': ['normal', '使能够设置移动网络的策略。', '允许应用程序设置与移动网络相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_MODIFY_USERS': ['normal', '允许策略管理以防止用户修改。', '允许应用程序管理防止用户修改用户的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL'],
        'MANAGE_DEVICE_POLICY_MTE': ['normal', '使能够管理内存标记扩展的策略。', '允许应用程序管理与内存标记扩展（MTE）相关的策略。'],
        'MANAGE_DEVICE_POLICY_NEARBY_COMMUNICATION': ['normal', '允许设置附近通信的策略。', '允许应用程序设置与附近通信（例如Beam和附近流媒体）相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_NETWORK_LOGGING': ['normal', '使能够设置网络日志记录的策略。', '允许应用程序设置与网络日志记录相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_ORGANIZATION_IDENTITY': ['normal', '允许管理管理组织的身份。', '允许应用程序管理管理组织的身份。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_OVERRIDE_APN': ['normal', '允许设置覆盖APN的策略。', '允许应用程序设置与覆盖APN相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PACKAGE_STATE': ['normal', '使能够设置隐藏和暂停软件包的策略。', '允许应用程序设置与隐藏和暂停软件包相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_PHYSICAL_MEDIA': ['normal', '允许设置物理媒体使用的策略。', '允许应用程序设置与物理媒体相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PRINTING': ['normal', '允许设置打印服务的策略。', '允许应用程序设置与打印相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PRIVATE_DNS': ['normal', '允许设置私有DNS管理的策略。', '允许应用程序设置与私有DNS相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PROFILES': ['normal', '允许设置用户配置文件的策略。', '允许应用程序设置与配置文件相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PROFILE_INTERACTION': ['normal', '允许设置用户配置文件之间交互的策略。', '允许应用程序设置与配置文件交互相关的策略（例如禁止跨配置文件复制和粘贴）。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_PROXY': ['normal', '允许独立于网络设置全局HTTP代理。', '允许应用程序设置与网络无关的全局HTTP代理。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_QUERY_SYSTEM_UPDATES': ['normal', '允许查询系统更新。', '允许应用程序查询系统更新。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_RESET_PASSWORD': ['normal', '允许强制设置新的设备解锁密码或配置文件挑战。', '允许应用程序强制设置当前用户的新设备解锁密码或管理的配置文件挑战。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_RESTRICT_PRIVATE_DNS': ['normal', '允许限制用户配置私有DNS。', '允许应用程序设置与限制用户配置私有DNS相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_RUNTIME_PERMISSIONS': ['normal', '允许设置软件包的运行时权限。', '允许应用程序设置软件包上运行时权限的授予状态。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_RUN_IN_BACKGROUND': ['normal', '允许设置后台进程管理的策略。', '允许应用程序设置与用户在后台运行相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SAFE_BOOT': ['normal', '允许管理安全启动模式的策略。', '允许应用程序管理安全启动策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SCREEN_CAPTURE': ['normal', '允许设置屏幕捕获功能的策略。', '允许应用程序设置与屏幕捕获相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_SCREEN_CONTENT': ['normal', '允许设置屏幕内容使用的策略。', '允许应用程序设置与屏幕内容使用相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SECURITY_LOGGING': ['normal', '允许设置安全日志记录的策略。', '允许应用程序设置与安全日志记录相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SETTINGS': ['normal', '允许设置一般设备策略。', '允许应用程序设置与设置相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SMS': ['normal', '允许设置短信功能的策略。', '允许应用程序设置与短信相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_STATUS_BAR': ['normal', '允许设置状态栏的策略。', '允许应用程序设置与状态栏相关的策略。'],
        'MANAGE_DEVICE_POLICY_SUPPORT_MESSAGE': ['normal', '允许为受策略影响的操作设置支持消息。', '允许应用程序为用户操作受活动策略影响时设置支持消息。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SUSPEND_PERSONAL_APPS': ['normal', '允许通过策略设置暂停个人应用。', '允许应用程序设置与暂停个人应用相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_APPS': ['normal', '允许管理与系统应用相关的策略。', '允许应用程序管理与系统应用相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_DIALOGS': ['normal', '允许设置系统对话框的策略。', '允许应用程序设置与系统对话框相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_SYSTEM_UPDATES': ['normal', '允许设置系统更新的策略。', '允许应用程序设置与系统更新相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_TIME': ['normal', '允许管理与时间设置相关的策略。', '允许应用程序管理与时间相关的设备策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_USB_DATA_SIGNALLING': ['normal', '允许设置USB数据信号的策略。', '允许应用程序设置与USB数据信号相关的策略。'],
        'MANAGE_DEVICE_POLICY_USB_FILE_TRANSFER': ['normal', '允许设置USB文件传输的策略。', '允许应用程序设置与USB文件传输相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_USERS': ['normal', '允许设置与用户管理相关的策略。', '允许应用程序设置与用户相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_VPN': ['normal', '允许设置VPN使用的策略。', '允许应用程序设置与VPN相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_WALLPAPER': ['normal', '允许设置壁纸管理的策略。', '允许应用程序设置与壁纸相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_WIFI': ['normal', '允许设置WiFi连接的策略。', '允许应用程序设置与Wifi相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_DEVICE_POLICY_WINDOWS': ['normal', '允许设置窗口管理的策略。', '允许应用程序设置与窗口相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL。'],
        'MANAGE_DEVICE_POLICY_WIPE_DATA': ['normal', '允许管理数据擦除的策略。', '允许应用程序管理与擦除数据相关的策略。要在与调用用户不同的用户上调用受此权限保护的API，需要Manifest.permission#MANAGE_DEVICE_POLICY_ACROSS_USERS。'],
        'MANAGE_MEDIA': ['signature', '允许在没有用户确认的情况下修改和删除媒体文件。', '允许应用程序修改和删除此设备上或任何连接的存储设备上的媒体文件，而无需用户确认。应用程序必须已被授予READ_EXTERNAL_STORAGE或MANAGE_EXTERNAL_STORAGE权限，此权限才能生效。'],
        'MANAGE_WIFI_INTERFACES': ['normal', '允许管理Wi-Fi接口请求之间的冲突。', '允许应用程序在无法满足Wi-Fi接口请求而不拆除一个或多个其他接口时得到通知，并提供是批准请求还是拒绝请求的决定。不供第三方应用程序使用。'],
        'MANAGE_WIFI_NETWORK_SELECTION': ['normal', '允许对Wi-Fi网络选择进行特权管理。', '此权限用于让OEM授予其受信任的应用程序访问一部分特权wifi API的权限，以提高wifi性能。允许应用程序管理与Wi-Fi网络选择相关的功能，如启用或禁用全局自动加入、修改连接扫描间隔和批准Wi-Fi Direct连接。不供第三方应用程序使用。'],
        'NEARBY_WIFI_DEVICES': ['dangerous', '通过Wi-Fi向附近设备广告和连接所需的权限。', '能够通过Wi-Fi向附近设备广告和连接所需的权限。'],
        'OVERRIDE_WIFI_CONFIG': ['normal', '允许修改任何Wi-Fi配置。', '允许应用程序修改任何wifi配置，即使是由另一个应用程序创建的。一旦重新配置，原始创建者就不能再进行任何修改。不供第三方应用程序使用；它用于应用程序保护自己免受除全局搜索之外的所有人的影响。'],
        'POST_NOTIFICATIONS': ['dangerous', '允许应用发布通知。', '允许应用发布通知'],
        'PROVIDE_OWN_AUTOFILL_SUGGESTIONS': ['internal', '允许使用自动填充框架提供自动填充建议。', '允许应用程序使用自动填充框架显示其建议。'],
        'PROVIDE_REMOTE_CREDENTIALS': ['signature', '允许存储和检索来自远程设备的凭据。', '允许应用程序能够存储和检索来自远程设备的凭据。'],
        'READ_ASSISTANT_APP_SEARCH_DATA': ['normal', '允许查询对助手角色可见的全局AppSearch数据。', "允许应用程序查询AppSearch中对ASSISTANT角色可见的全局数据。"],
        'READ_BASIC_PHONE_STATE': ['normal', '允许只读访问基本电话状态信息。', '允许只读访问带有非危险权限的电话状态，包括蜂窝网络类型、软件版本等信息。'],
        'READ_HOME_APP_SEARCH_DATA': ['normal', '允许查询对Home角色可见的全局AppSearch数据。', "允许应用程序查询AppSearch中对HOME角色可见的全局数据。"],
        'READ_MEDIA_AUDIO': ['dangerous', '允许从外部存储读取音频文件。', '允许应用程序从外部存储读取音频文件。'],
        'READ_MEDIA_IMAGES': ['dangerous', '允许从外部存储读取图像文件。', '允许应用程序从外部存储读取图像文件。'],
        'READ_MEDIA_VIDEO': ['dangerous', '允许从外部存储读取视频文件。', '允许应用程序从外部存储读取视频文件。'],
        'READ_MEDIA_VISUAL_USER_SELECTED': ['dangerous', '允许从外部存储读取用户选择的图像或视频文件。', '允许应用程序从外部存储读取用户通过权限提示照片选择器选择的图像或视频文件。应用程序可以检查此权限，以验证用户是否决定使用照片选择器，而不是授予对READ_MEDIA_IMAGES或READ_MEDIA_VIDEO的访问权限。它不会阻止应用程序手动访问标准照片选择器。此权限应与READ_MEDIA_IMAGES和/或READ_MEDIA_VIDEO一起请求，具体取决于所需的媒体类型。'],
        'READ_NEARBY_STREAMING_POLICY': ['normal', '允许读取附近流媒体策略设置。', '允许应用程序读取附近流媒体策略。该策略控制是否允许设备将其通知和应用程序流式传输到附近的设备。非设备所有者的应用程序将需要此权限来调用DevicePolicyManager.getNearbyNotificationStreamingPolicy()或DevicePolicyManager.getNearbyAppStreamingPolicy()。'],
        'REQUEST_COMPANION_PROFILE_APP_STREAMING': ['normal', '允许请求与用于应用程序流式传输的虚拟显示器关联。', '允许应用程序请求通过CompanionDeviceManager与能够流式传输Android应用程序的虚拟显示器（AssociationRequest.DEVICE_PROFILE_APP_STREAMING）关联。不供第三方应用程序使用。'],
        'REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION': ['normal', '允许请求与用于汽车投影的车辆头部单元关联。', '允许应用程序请求通过CompanionDeviceManager与能够进行汽车投影的车辆头部单元（AssociationRequest.DEVICE_PROFILE_AUTOMOTIVE_PROJECTION）关联。不供第三方应用程序使用。'],
        'REQUEST_COMPANION_PROFILE_COMPUTER': ['normal', '允许请求与计算机关联以共享功能。', '允许应用程序请求与计算机关联，以与其他设备共享功能和/或数据，如通知、照片和媒体（AssociationRequest.DEVICE_PROFILE_COMPUTER），通过CompanionDeviceManager。不供第三方应用程序使用。'],
        'REQUEST_COMPANION_PROFILE_GLASSES': ['normal', "允许请求将设备关联为'眼镜'。", '允许应用程序请求通过CompanionDeviceManager将设备关联为"眼镜"'],
        'REQUEST_COMPANION_PROFILE_NEARBY_DEVICE_STREAMING': ['normal', '允许请求向附近设备流式传输内容。', '允许应用程序请求通过CompanionDeviceManager从Android主机向附近设备流式传输内容（AssociationRequest.DEVICE_PROFILE_NEARBY_DEVICE_STREAMING）。不供第三方应用程序使用。'],
        'REQUEST_COMPANION_SELF_MANAGED': ['normal', '允许创建自管理的伴侣设备关联。', '允许应用程序创建"自管理"关联。'],
        'REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND': ['normal', '允许伴侣应用从后台启动前台服务。', '允许伴侣应用从后台启动前台服务。'],
        'RUN_USER_INITIATED_JOBS': ['normal', '允许使用用户发起的作业API。', '允许应用程序使用用户发起的作业API。有关更多详细信息，请参阅JobInfo.Builder.setUserInitiated(boolean)。'],
        'START_FOREGROUND_SERVICES_FROM_BACKGROUND': ['normal', '允许从后台启动前台服务。', "允许应用程序随时从后台启动前台服务。此权限不供第三方应用程序使用，唯一的例外是应用程序是默认的短信应用程序。否则，它只能由特权应用程序、应用程序验证器应用程序以及具有任何紧急或系统图库角色的应用程序使用。"],
        'START_VIEW_APP_FEATURES': ['signature', '允许启动列出应用功能的屏幕。', '允许持有者启动带有应用功能列表的屏幕。'],
        'SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE': ['signature', '允许订阅键盘锁定状态。', '允许应用程序订阅键盘锁定（即显示）状态。'],
        'TURN_SCREEN_ON': ['normal', '允许打开屏幕，供家庭自动化应用使用。', '允许应用程序打开屏幕，例如使用PowerManager.ACQUIRE_CAUSES_WAKEUP。仅供家庭自动化应用使用。'],
        'UPDATE_PACKAGES_WITHOUT_USER_ACTION': ['normal', '允许在不需要用户操作的情况下更新软件包。', '允许应用程序通过PackageInstaller.SessionParams.setRequireUserAction(int)指示应用程序更新不应要求用户操作。'],
        'USE_EXACT_ALARM': ['normal', '允许在没有用户权限的情况下使用精确闹钟。', '允许应用程序使用精确闹钟，就像使用SCHEDULE_EXACT_ALARM一样，但不需要向用户请求此权限。这仅适用于将精确闹钟作为其核心功能的应用程序。如果您的应用程序需要精确闹钟用于用户可能在您的应用程序内使用或不使用的次要功能，您应继续使用SCHEDULE_EXACT_ALARM。请记住，这是一个强大的权限，应用商店可能会执行政策来审核和审查此权限的使用情况。如果发现应用程序滥用此权限，此类审核可能涉及从应用商店中删除。'],
        'UWB_RANGING': ['dangerous', '使用超宽带对设备进行测距所需的权限。', '能够使用超宽带对设备进行测距所需的权限。'],
        'ACCESS_HIDDEN_PROFILES': ['normal', '通过声明ACCESS_HIDDEN_PROFILES权限添加对私人空间的支持。', '允许应用程序访问具有android.content.pm.UserProperties#PROFILE_API_VISIBILITY_HIDDEN用户属性的配置文件，例如UserManager.USER_TYPE_PROFILE_PRIVATE。'],
        'BIND_APP_FUNCTION_SERVICE': ['signature', '这必须由AppFunctionService要求，以确保只有系统才能绑定到它。', '必须由AppFunctionService要求，以确保只有系统才能绑定到它。'],
        'FOREGROUND_SERVICE_MEDIA_PROCESSING': ['normal', '允许普通应用程序使用类型为"mediaProcessing"的Service.startForeground。', '允许普通应用程序使用类型为"mediaProcessing"的Service.startForeground。'],
        'MANAGE_DEVICE_POLICY_ASSIST_CONTENT': ['internal', '授予应用程序配置与特权应用（如助手应用）共享辅助内容的策略的能力。', '允许应用程序设置与向特权应用（如助手应用）发送辅助内容相关的策略。'],
        'DETECT_SCREEN_RECORDING': ['normal', '授予应用程序在音频或屏幕录制进行时接收通知的能力。', '允许应用程序在被录制时得到通知。'],
        'MANAGE_DEVICE_POLICY_BLOCK_UNINSTALL': ['internal', '允许应用程序控制防止卸载特定软件包的策略。', '允许应用程序管理与阻止软件包卸载相关的策略。'],
        'MANAGE_DEVICE_POLICY_CAMERA_TOGGLE': ['internal', '允许应用程序执行控制相机开关状态的策略。', '允许应用程序管理与相机开关相关的策略。'],
        'MANAGE_DEVICE_POLICY_CONTENT_PROTECTION': ['internal', '授予应用程序执行限制指定软件包卸载的策略的能力。', '允许应用程序管理与内容保护相关的策略。'],
        'MANAGE_DEVICE_POLICY_MANAGED_SUBSCRIPTIONS': ['internal', '授予应用程序配置管理员下载的订阅管理策略的能力。', '允许应用程序设置与管理员下载的订阅相关的策略。'],
        'MANAGE_DEVICE_POLICY_MICROPHONE_TOGGLE': ['internal', '授予应用程序控制麦克风开关状态管理策略的能力。', '允许应用程序管理与麦克风开关相关的策略。'],
        'MEDIA_ROUTING_CONTROL': ['normal', '允许应用程序管理媒体应用程序的路由，仅限于COMPANION_DEVICE_WATCH角色使用。', '允许应用程序控制媒体应用程序的路由。仅供COMPANION_DEVICE_WATCH角色使用'],
        'READ_DROPBOX_DATA': ['normal', '允许应用程序访问存储在Dropbox中的数据，专门用于系统级或第一方应用程序，不适用于第三方应用程序。', '允许应用程序访问Dropbox中的数据。不供第三方应用程序使用。'],
        'SET_BIOMETRIC_DIALOG_ADVANCED': ['normal', '允许应用程序自定义BiometricDialog功能，包括徽标和内容视图。仅限系统使用。', '允许应用程序在BiometricDialog（SystemUI）上设置高级功能，包括徽标、徽标描述和带有更多选项按钮的内容视图。不供第三方应用程序使用。'],
        'ACCESS_ORIENTATION': ['normal', '允许应用程序访问设备的方向。', '允许应用程序访问设备的方向。'],
    },

    'SPECIAL_PERMISSIONS': {
        'com.sec.android.provider.badge.permission.READ': ['normal', '在应用上显示通知计数', '在三星手机的应用启动图标上显示通知计数或徽章。'],
        'com.sec.android.provider.badge.permission.WRITE': ['normal', '在应用上显示通知计数', '在三星手机的应用启动图标上显示通知计数或徽章。'],
        'com.htc.launcher.permission.READ_SETTINGS': ['normal', '在应用上显示通知计数', '在htc手机的应用启动图标上显示通知计数或徽章。'],
        'com.htc.launcher.permission.UPDATE_SHORTCUT': ['normal', '在应用上显示通知计数', '在htc手机的应用启动图标上显示通知计数或徽章。'],
        'com.sonyericsson.home.permission.BROADCAST_BADGE': ['normal', '在应用上显示通知计数', '在索尼手机的应用启动图标上显示通知计数或徽章。'],
        'com.sonymobile.home.permission.PROVIDER_INSERT_BADGE': ['normal', '在应用上显示通知计数', '在索尼手机的应用启动图标上显示通知计数或徽章。'],
        'com.anddoes.launcher.permission.UPDATE_COUNT': ['normal', '在应用上显示通知计数', '在apex上的应用启动图标上显示通知计数或徽章。'],
        'com.majeur.launcher.permission.UPDATE_BADGE': ['normal', '在应用上显示通知计数', '在solid上的应用启动图标上显示通知计数或徽章。'],
        'com.huawei.android.launcher.permission.READ_SETTINGS': ['normal', '在应用上显示通知计数', '在华为手机的应用启动图标上显示通知计数或徽章。'],
        'com.huawei.android.launcher.permission.WRITE_SETTINGS': ['normal', '在应用上显示通知计数', '在华为手机的应用启动图标上显示通知计数或徽章。'],
        'com.huawei.android.launcher.permission.CHANGE_BADGE': ['normal', '在应用上显示通知计数', '在华为手机的应用启动图标上显示通知计数或徽章。'],
        'com.oppo.launcher.permission.READ_SETTINGS': ['normal', '在应用上显示通知计数', '在oppo手机的应用启动图标上显示通知计数或徽章。'],
        'com.oppo.launcher.permission.WRITE_SETTINGS': ['normal', '在应用上显示通知计数', '在oppo手机的应用启动图标上显示通知计数或徽章。'],
        'com.google.android.gms.permission.AD_ID': ['normal', '应用显示广告', '此应用使用Google广告ID，可能会提供广告。'],
        'com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE': ['normal', '由谷歌定义的权限', '由谷歌定义的自定义权限。'],
        'com.google.android.c2dm.permission.RECEIVE': ['normal', '接收推送通知', '允许应用程序从云接收推送通知。'],
        'com.android.vending.BILLING': ['normal', '应用有应用内购买', '允许应用程序从Google Play进行应用内购买。'],
        'android.permission.ACCESS_ADSERVICES_TOPICS': ['normal', '允许应用程序访问广告服务主题', '这使应用程序能够检索与广告主题或兴趣相关的信息，可用于定向广告目的。'],
        'android.permission.ACCESS_ADSERVICES_ATTRIBUTION': ['normal', '允许应用程序访问广告服务归因', '这使应用程序能够检索与广告归因相关的信息，可用于定向广告目的。应用程序可以收集有关用户如何与广告交互的数据，如点击或展示，以衡量广告活动的有效性。'],
        'android.permission.ACCESS_ADSERVICES_AD_ID': ['normal', '允许应用访问设备的广告ID。', '这个ID是由Google的广告服务提供的唯一的、用户可重置的标识符，允许应用程序跟踪用户行为用于广告目的，同时保持用户隐私。'],
        'oppo.permission.OPPO_COMPONENT_SAFE': ['signature', 'OPPO设备特有的权限', '它用于授予应用程序访问某些系统级功能或组件的能力，这些功能或组件出于安全原因而被限制。此权限确保只有受信任的应用程序才能与OPPO系统的敏感部分交互。'],
        'com.huawei.permission.external_app_settings.USE_COMPONENT': ['signature', '华为设备特有的权限', '它用于授予应用程序访问某些系统级功能或组件的能力，这些功能或组件出于安全原因而被限制。此权限确保只有受信任的应用程序才能与华为系统的敏感部分交互。'],

    },

    'MANIFEST_PERMISSION_GROUP': {
        'ACCOUNTS': '直接访问由账户管理器管理的账户的权限。',
        'COST_MONEY': '用于可能使用户花钱而无需其直接参与的权限。',
        'DEVELOPMENT_TOOLS': '与开发功能相关的权限组。',
        'HARDWARE_CONTROLS': '用于提供对设备上硬件的直接访问的权限。',
        'LOCATION': '用于允许访问用户当前位置的权限。',
        'MESSAGES': '用于允许应用程序代表用户发送消息或拦截用户接收的消息的权限。',
        'NETWORK': '用于提供对网络服务的访问的权限。',
        'PERSONAL_INFO': '用于提供对用户私人数据的访问的权限，如联系人、日历事件、电子邮件等。',
        'PHONE_CALLS': '与访问和修改电话状态相关的权限：拦截外拨电话，读取和修改电话状态。',
        'STORAGE': '与SD卡访问相关的权限组。',
        'SYSTEM_TOOLS': '与系统API相关的权限组。',
    },
}